execute @e[tag=system,scores={upgrade=2400}] ~ ~ ~ title @a title §6§bl120
execute @e[tag=system,scores={upgrade=2380}] ~ ~ ~ title @a title §6§bl119
execute @e[tag=system,scores={upgrade=2360}] ~ ~ ~ title @a title §6§bl118
execute @e[tag=system,scores={upgrade=2340}] ~ ~ ~ title @a title §6§bl117
execute @e[tag=system,scores={upgrade=2320}] ~ ~ ~ title @a title §6§bl116
execute @e[tag=system,scores={upgrade=2300}] ~ ~ ~ title @a title §6§bl115
execute @e[tag=system,scores={upgrade=2280}] ~ ~ ~ title @a title §6§bl114
execute @e[tag=system,scores={upgrade=2260}] ~ ~ ~ title @a title §6§bl113
execute @e[tag=system,scores={upgrade=2240}] ~ ~ ~ title @a title §6§bl112
execute @e[tag=system,scores={upgrade=2220}] ~ ~ ~ title @a title §6§bl111
execute @e[tag=system,scores={upgrade=2200}] ~ ~ ~ title @a title §6§bl110
execute @e[tag=system,scores={upgrade=2180}] ~ ~ ~ title @a title §6§bl109
execute @e[tag=system,scores={upgrade=2160}] ~ ~ ~ title @a title §6§bl108
execute @e[tag=system,scores={upgrade=2140}] ~ ~ ~ title @a title §6§bl107
execute @e[tag=system,scores={upgrade=2120}] ~ ~ ~ title @a title §6§bl106
execute @e[tag=system,scores={upgrade=2100}] ~ ~ ~ title @a title §6§bl105
execute @e[tag=system,scores={upgrade=2080}] ~ ~ ~ title @a title §6§bl104
execute @e[tag=system,scores={upgrade=2060}] ~ ~ ~ title @a title §6§bl103
execute @e[tag=system,scores={upgrade=2040}] ~ ~ ~ title @a title §6§bl102
execute @e[tag=system,scores={upgrade=2020}] ~ ~ ~ title @a title §6§bl101
execute @e[tag=system,scores={upgrade=2000}] ~ ~ ~ title @a title §6§bl100
execute @e[tag=system,scores={upgrade=1980}] ~ ~ ~ title @a title §6§bl99
execute @e[tag=system,scores={upgrade=1960}] ~ ~ ~ title @a title §6§bl98
execute @e[tag=system,scores={upgrade=1940}] ~ ~ ~ title @a title §6§bl97
execute @e[tag=system,scores={upgrade=1920}] ~ ~ ~ title @a title §6§bl96
execute @e[tag=system,scores={upgrade=1900}] ~ ~ ~ title @a title §6§bl95
execute @e[tag=system,scores={upgrade=1880}] ~ ~ ~ title @a title §6§bl94
execute @e[tag=system,scores={upgrade=1860}] ~ ~ ~ title @a title §6§bl93
execute @e[tag=system,scores={upgrade=1840}] ~ ~ ~ title @a title §6§bl92
execute @e[tag=system,scores={upgrade=1820}] ~ ~ ~ title @a title §6§bl91
execute @e[tag=system,scores={upgrade=1800}] ~ ~ ~ title @a title §6§bl90
execute @e[tag=system,scores={upgrade=1780}] ~ ~ ~ title @a title §6§bl89
execute @e[tag=system,scores={upgrade=1760}] ~ ~ ~ title @a title §6§bl88
execute @e[tag=system,scores={upgrade=1740}] ~ ~ ~ title @a title §6§bl87
execute @e[tag=system,scores={upgrade=1720}] ~ ~ ~ title @a title §6§bl86
execute @e[tag=system,scores={upgrade=1700}] ~ ~ ~ title @a title §6§bl85
execute @e[tag=system,scores={upgrade=1680}] ~ ~ ~ title @a title §6§bl84
execute @e[tag=system,scores={upgrade=1660}] ~ ~ ~ title @a title §6§bl83
execute @e[tag=system,scores={upgrade=1640}] ~ ~ ~ title @a title §6§bl82
execute @e[tag=system,scores={upgrade=1620}] ~ ~ ~ title @a title §6§bl81
execute @e[tag=system,scores={upgrade=1600}] ~ ~ ~ title @a title §6§bl80
execute @e[tag=system,scores={upgrade=1580}] ~ ~ ~ title @a title §6§bl79
execute @e[tag=system,scores={upgrade=1560}] ~ ~ ~ title @a title §6§bl78
execute @e[tag=system,scores={upgrade=1540}] ~ ~ ~ title @a title §6§bl77
execute @e[tag=system,scores={upgrade=1520}] ~ ~ ~ title @a title §6§bl76
execute @e[tag=system,scores={upgrade=1500}] ~ ~ ~ title @a title §6§bl75
execute @e[tag=system,scores={upgrade=1480}] ~ ~ ~ title @a title §6§bl74
execute @e[tag=system,scores={upgrade=1460}] ~ ~ ~ title @a title §6§bl73
execute @e[tag=system,scores={upgrade=1440}] ~ ~ ~ title @a title §6§bl72
execute @e[tag=system,scores={upgrade=1420}] ~ ~ ~ title @a title §6§bl71
execute @e[tag=system,scores={upgrade=1400}] ~ ~ ~ title @a title §6§bl70
execute @e[tag=system,scores={upgrade=1380}] ~ ~ ~ title @a title §6§bl69
execute @e[tag=system,scores={upgrade=1360}] ~ ~ ~ title @a title §6§bl68
execute @e[tag=system,scores={upgrade=1340}] ~ ~ ~ title @a title §6§bl67
execute @e[tag=system,scores={upgrade=1320}] ~ ~ ~ title @a title §6§bl66
execute @e[tag=system,scores={upgrade=1300}] ~ ~ ~ title @a title §6§bl65
execute @e[tag=system,scores={upgrade=1280}] ~ ~ ~ title @a title §6§bl64
execute @e[tag=system,scores={upgrade=1260}] ~ ~ ~ title @a title §6§bl63
execute @e[tag=system,scores={upgrade=1240}] ~ ~ ~ title @a title §6§bl62
execute @e[tag=system,scores={upgrade=1220}] ~ ~ ~ title @a title §6§bl61
execute @e[tag=system,scores={upgrade=1200}] ~ ~ ~ title @a title §6§bl60
execute @e[tag=system,scores={upgrade=1180}] ~ ~ ~ title @a title §6§bl59
execute @e[tag=system,scores={upgrade=1160}] ~ ~ ~ title @a title §6§bl58
execute @e[tag=system,scores={upgrade=1140}] ~ ~ ~ title @a title §6§bl57
execute @e[tag=system,scores={upgrade=1120}] ~ ~ ~ title @a title §6§bl56
execute @e[tag=system,scores={upgrade=1100}] ~ ~ ~ title @a title §6§bl55
execute @e[tag=system,scores={upgrade=1080}] ~ ~ ~ title @a title §6§bl54
execute @e[tag=system,scores={upgrade=1060}] ~ ~ ~ title @a title §6§bl53
execute @e[tag=system,scores={upgrade=1040}] ~ ~ ~ title @a title §6§bl52
execute @e[tag=system,scores={upgrade=1020}] ~ ~ ~ title @a title §6§bl51
execute @e[tag=system,scores={upgrade=1000}] ~ ~ ~ title @a title §6§bl50
execute @e[tag=system,scores={upgrade=980}] ~ ~ ~ title @a title §6§bl49
execute @e[tag=system,scores={upgrade=960}] ~ ~ ~ title @a title §6§bl48
execute @e[tag=system,scores={upgrade=940}] ~ ~ ~ title @a title §6§bl47
execute @e[tag=system,scores={upgrade=920}] ~ ~ ~ title @a title §6§bl46
execute @e[tag=system,scores={upgrade=900}] ~ ~ ~ title @a title §6§bl45
execute @e[tag=system,scores={upgrade=880}] ~ ~ ~ title @a title §6§bl44
execute @e[tag=system,scores={upgrade=860}] ~ ~ ~ title @a title §6§bl43
execute @e[tag=system,scores={upgrade=840}] ~ ~ ~ title @a title §6§bl42
execute @e[tag=system,scores={upgrade=820}] ~ ~ ~ title @a title §6§bl41
execute @e[tag=system,scores={upgrade=800}] ~ ~ ~ title @a title §6§bl40
execute @e[tag=system,scores={upgrade=780}] ~ ~ ~ title @a title §6§bl39
execute @e[tag=system,scores={upgrade=760}] ~ ~ ~ title @a title §6§bl38
execute @e[tag=system,scores={upgrade=740}] ~ ~ ~ title @a title §6§bl37
execute @e[tag=system,scores={upgrade=720}] ~ ~ ~ title @a title §6§bl36
execute @e[tag=system,scores={upgrade=700}] ~ ~ ~ title @a title §6§bl35
execute @e[tag=system,scores={upgrade=680}] ~ ~ ~ title @a title §6§bl34
execute @e[tag=system,scores={upgrade=660}] ~ ~ ~ title @a title §6§bl33
execute @e[tag=system,scores={upgrade=640}] ~ ~ ~ title @a title §6§bl32
execute @e[tag=system,scores={upgrade=620}] ~ ~ ~ title @a title §6§bl31
execute @e[tag=system,scores={upgrade=600}] ~ ~ ~ title @a title §6§bl30
execute @e[tag=system,scores={upgrade=580}] ~ ~ ~ title @a title §6§bl29
execute @e[tag=system,scores={upgrade=560}] ~ ~ ~ title @a title §6§bl28
execute @e[tag=system,scores={upgrade=540}] ~ ~ ~ title @a title §6§bl27
execute @e[tag=system,scores={upgrade=520}] ~ ~ ~ title @a title §6§bl26
execute @e[tag=system,scores={upgrade=500}] ~ ~ ~ title @a title §6§bl25
execute @e[tag=system,scores={upgrade=480}] ~ ~ ~ title @a title §6§bl24
execute @e[tag=system,scores={upgrade=460}] ~ ~ ~ title @a title §6§bl23
execute @e[tag=system,scores={upgrade=440}] ~ ~ ~ title @a title §6§bl22
execute @e[tag=system,scores={upgrade=420}] ~ ~ ~ title @a title §6§bl21
execute @e[tag=system,scores={upgrade=400}] ~ ~ ~ title @a title §6§bl20
execute @e[tag=system,scores={upgrade=380}] ~ ~ ~ title @a title §6§bl19
execute @e[tag=system,scores={upgrade=360}] ~ ~ ~ title @a title §6§bl18
execute @e[tag=system,scores={upgrade=340}] ~ ~ ~ title @a title §6§bl17
execute @e[tag=system,scores={upgrade=320}] ~ ~ ~ title @a title §6§bl16
execute @e[tag=system,scores={upgrade=300}] ~ ~ ~ title @a title §6§bl15
execute @e[tag=system,scores={upgrade=280}] ~ ~ ~ title @a title §6§bl14
execute @e[tag=system,scores={upgrade=260}] ~ ~ ~ title @a title §6§bl13
execute @e[tag=system,scores={upgrade=240}] ~ ~ ~ title @a title §6§bl12
execute @e[tag=system,scores={upgrade=220}] ~ ~ ~ title @a title §6§bl11
execute @e[tag=system,scores={upgrade=200}] ~ ~ ~ title @a title §6§bl10 
execute @e[tag=system,scores={upgrade=180}] ~ ~ ~ title @a title §6§bl9
execute @e[tag=system,scores={upgrade=160}] ~ ~ ~ title @a title §6§bl8
execute @e[tag=system,scores={upgrade=140}] ~ ~ ~ title @a title §6§bl7
execute @e[tag=system,scores={upgrade=120}] ~ ~ ~ title @a title §6§bl6
execute @e[tag=system,scores={upgrade=100}] ~ ~ ~ title @a title §6§bl5
execute @e[tag=system,scores={upgrade=80}] ~ ~ ~ title @a title §6§bl4
execute @e[tag=system,scores={upgrade=60}] ~ ~ ~ title @a title §6§bl3
execute @e[tag=system,scores={upgrade=40}] ~ ~ ~ title @a title §6§bl2
execute @e[tag=system,scores={upgrade=20}] ~ ~ ~ title @a title §6§bl1
execute @e[tag=system,scores={upgrade=..5}] ~ ~ ~ title @a clear