execute @e[tag=system,scores={upgrade=2400}] ~ ~ ~ title @a title §6§l120
execute @e[tag=system,scores={upgrade=2380}] ~ ~ ~ title @a title §6§l119
execute @e[tag=system,scores={upgrade=2360}] ~ ~ ~ title @a title §6§l118
execute @e[tag=system,scores={upgrade=2340}] ~ ~ ~ title @a title §6§l117
execute @e[tag=system,scores={upgrade=2320}] ~ ~ ~ title @a title §6§l116
execute @e[tag=system,scores={upgrade=2300}] ~ ~ ~ title @a title §6§l115
execute @e[tag=system,scores={upgrade=2280}] ~ ~ ~ title @a title §6§l114
execute @e[tag=system,scores={upgrade=2260}] ~ ~ ~ title @a title §6§l113
execute @e[tag=system,scores={upgrade=2240}] ~ ~ ~ title @a title §6§l112
execute @e[tag=system,scores={upgrade=2220}] ~ ~ ~ title @a title §6§l111
execute @e[tag=system,scores={upgrade=2200}] ~ ~ ~ title @a title §6§l110
execute @e[tag=system,scores={upgrade=2180}] ~ ~ ~ title @a title §6§l109
execute @e[tag=system,scores={upgrade=2160}] ~ ~ ~ title @a title §6§l108
execute @e[tag=system,scores={upgrade=2140}] ~ ~ ~ title @a title §6§l107
execute @e[tag=system,scores={upgrade=2120}] ~ ~ ~ title @a title §6§l106
execute @e[tag=system,scores={upgrade=2100}] ~ ~ ~ title @a title §6§l105
execute @e[tag=system,scores={upgrade=2080}] ~ ~ ~ title @a title §6§l104
execute @e[tag=system,scores={upgrade=2060}] ~ ~ ~ title @a title §6§l103
execute @e[tag=system,scores={upgrade=2040}] ~ ~ ~ title @a title §6§l102
execute @e[tag=system,scores={upgrade=2020}] ~ ~ ~ title @a title §6§l101
execute @e[tag=system,scores={upgrade=2000}] ~ ~ ~ title @a title §6§l100
execute @e[tag=system,scores={upgrade=1980}] ~ ~ ~ title @a title §6§l99
execute @e[tag=system,scores={upgrade=1960}] ~ ~ ~ title @a title §6§l98
execute @e[tag=system,scores={upgrade=1940}] ~ ~ ~ title @a title §6§l97
execute @e[tag=system,scores={upgrade=1920}] ~ ~ ~ title @a title §6§l96
execute @e[tag=system,scores={upgrade=1900}] ~ ~ ~ title @a title §6§l95
execute @e[tag=system,scores={upgrade=1880}] ~ ~ ~ title @a title §6§l94
execute @e[tag=system,scores={upgrade=1860}] ~ ~ ~ title @a title §6§l93
execute @e[tag=system,scores={upgrade=1840}] ~ ~ ~ title @a title §6§l92
execute @e[tag=system,scores={upgrade=1820}] ~ ~ ~ title @a title §6§l91
execute @e[tag=system,scores={upgrade=1800}] ~ ~ ~ title @a title §6§l90
execute @e[tag=system,scores={upgrade=1780}] ~ ~ ~ title @a title §6§l89
execute @e[tag=system,scores={upgrade=1760}] ~ ~ ~ title @a title §6§l88
execute @e[tag=system,scores={upgrade=1740}] ~ ~ ~ title @a title §6§l87
execute @e[tag=system,scores={upgrade=1720}] ~ ~ ~ title @a title §6§l86
execute @e[tag=system,scores={upgrade=1700}] ~ ~ ~ title @a title §6§l85
execute @e[tag=system,scores={upgrade=1680}] ~ ~ ~ title @a title §6§l84
execute @e[tag=system,scores={upgrade=1660}] ~ ~ ~ title @a title §6§l83
execute @e[tag=system,scores={upgrade=1640}] ~ ~ ~ title @a title §6§l82
execute @e[tag=system,scores={upgrade=1620}] ~ ~ ~ title @a title §6§l81
execute @e[tag=system,scores={upgrade=1600}] ~ ~ ~ title @a title §6§l80
execute @e[tag=system,scores={upgrade=1580}] ~ ~ ~ title @a title §6§l79
execute @e[tag=system,scores={upgrade=1560}] ~ ~ ~ title @a title §6§l78
execute @e[tag=system,scores={upgrade=1540}] ~ ~ ~ title @a title §6§l77
execute @e[tag=system,scores={upgrade=1520}] ~ ~ ~ title @a title §6§l76
execute @e[tag=system,scores={upgrade=1500}] ~ ~ ~ title @a title §6§l75
execute @e[tag=system,scores={upgrade=1480}] ~ ~ ~ title @a title §6§l74
execute @e[tag=system,scores={upgrade=1460}] ~ ~ ~ title @a title §6§l73
execute @e[tag=system,scores={upgrade=1440}] ~ ~ ~ title @a title §6§l72
execute @e[tag=system,scores={upgrade=1420}] ~ ~ ~ title @a title §6§l71
execute @e[tag=system,scores={upgrade=1400}] ~ ~ ~ title @a title §6§l70
execute @e[tag=system,scores={upgrade=1380}] ~ ~ ~ title @a title §6§l69
execute @e[tag=system,scores={upgrade=1360}] ~ ~ ~ title @a title §6§l68
execute @e[tag=system,scores={upgrade=1340}] ~ ~ ~ title @a title §6§l67
execute @e[tag=system,scores={upgrade=1320}] ~ ~ ~ title @a title §6§l66
execute @e[tag=system,scores={upgrade=1300}] ~ ~ ~ title @a title §6§l65
execute @e[tag=system,scores={upgrade=1280}] ~ ~ ~ title @a title §6§l64
execute @e[tag=system,scores={upgrade=1260}] ~ ~ ~ title @a title §6§l63
execute @e[tag=system,scores={upgrade=1240}] ~ ~ ~ title @a title §6§l62
execute @e[tag=system,scores={upgrade=1220}] ~ ~ ~ title @a title §6§l61
execute @e[tag=system,scores={upgrade=1200}] ~ ~ ~ title @a title §6§l60
execute @e[tag=system,scores={upgrade=1180}] ~ ~ ~ title @a title §6§l59
execute @e[tag=system,scores={upgrade=1160}] ~ ~ ~ title @a title §6§l58
execute @e[tag=system,scores={upgrade=1140}] ~ ~ ~ title @a title §6§l57
execute @e[tag=system,scores={upgrade=1120}] ~ ~ ~ title @a title §6§l56
execute @e[tag=system,scores={upgrade=1100}] ~ ~ ~ title @a title §6§l55
execute @e[tag=system,scores={upgrade=1080}] ~ ~ ~ title @a title §6§l54
execute @e[tag=system,scores={upgrade=1060}] ~ ~ ~ title @a title §6§l53
execute @e[tag=system,scores={upgrade=1040}] ~ ~ ~ title @a title §6§l52
execute @e[tag=system,scores={upgrade=1020}] ~ ~ ~ title @a title §6§l51
execute @e[tag=system,scores={upgrade=1000}] ~ ~ ~ title @a title §6§l50
execute @e[tag=system,scores={upgrade=980}] ~ ~ ~ title @a title §6§l49
execute @e[tag=system,scores={upgrade=960}] ~ ~ ~ title @a title §6§l48
execute @e[tag=system,scores={upgrade=940}] ~ ~ ~ title @a title §6§l47
execute @e[tag=system,scores={upgrade=920}] ~ ~ ~ title @a title §6§l46
execute @e[tag=system,scores={upgrade=900}] ~ ~ ~ title @a title §6§l45
execute @e[tag=system,scores={upgrade=880}] ~ ~ ~ title @a title §6§l44
execute @e[tag=system,scores={upgrade=860}] ~ ~ ~ title @a title §6§l43
execute @e[tag=system,scores={upgrade=840}] ~ ~ ~ title @a title §6§l42
execute @e[tag=system,scores={upgrade=820}] ~ ~ ~ title @a title §6§l41
execute @e[tag=system,scores={upgrade=800}] ~ ~ ~ title @a title §6§l40
execute @e[tag=system,scores={upgrade=780}] ~ ~ ~ title @a title §6§l39
execute @e[tag=system,scores={upgrade=760}] ~ ~ ~ title @a title §6§l38
execute @e[tag=system,scores={upgrade=740}] ~ ~ ~ title @a title §6§l37
execute @e[tag=system,scores={upgrade=720}] ~ ~ ~ title @a title §6§l36
execute @e[tag=system,scores={upgrade=700}] ~ ~ ~ title @a title §6§l35
execute @e[tag=system,scores={upgrade=680}] ~ ~ ~ title @a title §6§l34
execute @e[tag=system,scores={upgrade=660}] ~ ~ ~ title @a title §6§l33
execute @e[tag=system,scores={upgrade=640}] ~ ~ ~ title @a title §6§l32
execute @e[tag=system,scores={upgrade=620}] ~ ~ ~ title @a title §6§l31
execute @e[tag=system,scores={upgrade=600}] ~ ~ ~ title @a title §6§l30
execute @e[tag=system,scores={upgrade=580}] ~ ~ ~ title @a title §6§l29
execute @e[tag=system,scores={upgrade=560}] ~ ~ ~ title @a title §6§l28
execute @e[tag=system,scores={upgrade=540}] ~ ~ ~ title @a title §6§l27
execute @e[tag=system,scores={upgrade=520}] ~ ~ ~ title @a title §6§l26
execute @e[tag=system,scores={upgrade=500}] ~ ~ ~ title @a title §6§l25
execute @e[tag=system,scores={upgrade=480}] ~ ~ ~ title @a title §6§l24
execute @e[tag=system,scores={upgrade=460}] ~ ~ ~ title @a title §6§l23
execute @e[tag=system,scores={upgrade=440}] ~ ~ ~ title @a title §6§l22
execute @e[tag=system,scores={upgrade=420}] ~ ~ ~ title @a title §6§l21
execute @e[tag=system,scores={upgrade=400}] ~ ~ ~ title @a title §6§l20
execute @e[tag=system,scores={upgrade=380}] ~ ~ ~ title @a title §6§l19
execute @e[tag=system,scores={upgrade=360}] ~ ~ ~ title @a title §6§l18
execute @e[tag=system,scores={upgrade=340}] ~ ~ ~ title @a title §6§l17
execute @e[tag=system,scores={upgrade=320}] ~ ~ ~ title @a title §6§l16
execute @e[tag=system,scores={upgrade=300}] ~ ~ ~ title @a title §6§l15
execute @e[tag=system,scores={upgrade=280}] ~ ~ ~ title @a title §6§l14
execute @e[tag=system,scores={upgrade=260}] ~ ~ ~ title @a title §6§l13
execute @e[tag=system,scores={upgrade=240}] ~ ~ ~ title @a title §6§l12
execute @e[tag=system,scores={upgrade=220}] ~ ~ ~ title @a title §6§l11
execute @e[tag=system,scores={upgrade=200}] ~ ~ ~ title @a title §6§l10 
execute @e[tag=system,scores={upgrade=180}] ~ ~ ~ title @a title §6§l9
execute @e[tag=system,scores={upgrade=160}] ~ ~ ~ title @a title §6§l8
execute @e[tag=system,scores={upgrade=140}] ~ ~ ~ title @a title §6§l7
execute @e[tag=system,scores={upgrade=120}] ~ ~ ~ title @a title §6§l6
execute @e[tag=system,scores={upgrade=100}] ~ ~ ~ title @a title §6§l5
execute @e[tag=system,scores={upgrade=80}] ~ ~ ~ title @a title §6§l4
execute @e[tag=system,scores={upgrade=60}] ~ ~ ~ title @a title §6§l3
execute @e[tag=system,scores={upgrade=40}] ~ ~ ~ title @a title §6§l2
execute @e[tag=system,scores={upgrade=20}] ~ ~ ~ title @a title §6§l1
execute @e[tag=system,scores={upgrade=..5}] ~ ~ ~ title @a clear